// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller.js"
application.register("alert", AlertController)

import NestedFormController from "./nested_form_controller.js"
application.register("nested-form", NestedFormController)

import ProfileController from "./profile_controller.js"
application.register("profile", ProfileController)
