// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActiveNavLinkController from "./active_nav_link_controller.js"
application.register("active-nav-link", ActiveNavLinkController)

import AlertController from "./alert_controller.js"
application.register("alert", AlertController)

import DisplayController from "./display_controller.js"
application.register("display", DisplayController)

import DisplayMobileController from "./display_mobile_controller.js"
application.register("display-mobile", DisplayMobileController)

import NestedFormController from "./nested_form_controller.js"
application.register("nested-form", NestedFormController)
