// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ProfileController from "./profile_controller"
import AlertController from "./alert_controller"
import NestedFormController from "./nested_form_controller"

application.register("profile", ProfileController)
application.register("alert", AlertController)
application.register("nested_form", NestedFormController)
